import styled from "styled-components";

export default function Loading() {
  return (
    <Container>
      <div className="loadingio-spinner-eclipse-sndjdo3lc7i">
        <div className="ldio-aqefqaxsk5a">
          <div></div>
        </div>
      </div>
    </Container>
  );
}

const Container = styled.div`
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

  @keyframes ldio-aqefqaxsk5a {
    0% {
      transform: rotate(0deg);
    }
    50% {
      transform: rotate(180deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
  .ldio-aqefqaxsk5a div {
    position: absolute;
    animation: ldio-aqefqaxsk5a 1s linear infinite;
    width: 160px;
    height: 160px;
    top: 20px;
    left: 20px;
    border-radius: 50%;
    box-shadow: 0 4px 0 0 #126ba5;
    transform-origin: 80px 82px;
  }
  .loadingio-spinner-eclipse-sndjdo3lc7i {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: rgba(NaN, NaN, NaN, 0);
  }
  .ldio-aqefqaxsk5a {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-aqefqaxsk5a div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
